# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#

default_platform(:android)

platform :android do
  lane :build do |options|
    gradle(task: "assemble#{options[:flavor]}WebviewRelease")
    gradle(task: "assemble#{options[:flavor]}XwalkRelease")
  end

  lane :deploy do |options|
    version = ENV['RELEASE_VERSION'].empty? ? 'SNAPSHOT' : ENV['RELEASE_VERSION']
    package_name = options[:flavor] == 'unbranded' ? "org.medicmobile.webapp.mobile" : "org.medicmobile.webapp.mobile.#{options[:flavor]}"

    supply(
      package_name: package_name,
      track: "alpha",
      json_key: "playstore-secret.json",
      apk_paths: [
        "build/outputs/apk/#{options[:flavor]}Webview/release/medic-android-#{version}-#{options[:flavor]}-webview-arm64-v8a-release.apk",
        # NOT SUPPORTED WITH: targetSdkVersion 29. Need to add it back to support older Android versions
        # "build/outputs/apk/#{options[:flavor]}Webview/release/medic-android-#{version}-#{options[:flavor]}-webview-armeabi-v7a-release.apk",
        "build/outputs/apk/#{options[:flavor]}Xwalk/release/medic-android-#{version}-#{options[:flavor]}-xwalk-arm64-v8a-release.apk",
        "build/outputs/apk/#{options[:flavor]}Xwalk/release/medic-android-#{version}-#{options[:flavor]}-xwalk-armeabi-v7a-release.apk",
      ],
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      validate_only: false,

      timeout: 3600,
    )
  end
end
